# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [4]:
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742

In [11]:
b="The diameter of {} is {} kilometers"
print(b.format(planet,diameter))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [8]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [12]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [13]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [14]:
print(np.array([0 for i in range(0,10)]))

[0 0 0 0 0 0 0 0 0 0]


In [15]:
print(np.array([5 for i in range(5,10)]))

[5 5 5 5 5]


## 5. Create an array of all the even integers from 20 to 35

In [18]:
m=[i for i in range (20,36,2)]
print(np.array(m))

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [20]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [23]:
import pandas as pd


In [25]:
dream={'name':['deena','logu','thiyagu'],'age':[21,24,42]}
con=pd.DataFrame(dream)
print(con)


      name  age
0    deena   21
1     logu   24
2  thiyagu   42


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [33]:
start="2023-01-01"
end="2023-02-10"
dream=pd.date_range(start=start,end=end).to_pydatetime()
list(dream)

[datetime.datetime(2023, 1, 1, 0, 0),
 datetime.datetime(2023, 1, 2, 0, 0),
 datetime.datetime(2023, 1, 3, 0, 0),
 datetime.datetime(2023, 1, 4, 0, 0),
 datetime.datetime(2023, 1, 5, 0, 0),
 datetime.datetime(2023, 1, 6, 0, 0),
 datetime.datetime(2023, 1, 7, 0, 0),
 datetime.datetime(2023, 1, 8, 0, 0),
 datetime.datetime(2023, 1, 9, 0, 0),
 datetime.datetime(2023, 1, 10, 0, 0),
 datetime.datetime(2023, 1, 11, 0, 0),
 datetime.datetime(2023, 1, 12, 0, 0),
 datetime.datetime(2023, 1, 13, 0, 0),
 datetime.datetime(2023, 1, 14, 0, 0),
 datetime.datetime(2023, 1, 15, 0, 0),
 datetime.datetime(2023, 1, 16, 0, 0),
 datetime.datetime(2023, 1, 17, 0, 0),
 datetime.datetime(2023, 1, 18, 0, 0),
 datetime.datetime(2023, 1, 19, 0, 0),
 datetime.datetime(2023, 1, 20, 0, 0),
 datetime.datetime(2023, 1, 21, 0, 0),
 datetime.datetime(2023, 1, 22, 0, 0),
 datetime.datetime(2023, 1, 23, 0, 0),
 datetime.datetime(2023, 1, 24, 0, 0),
 datetime.datetime(2023, 1, 25, 0, 0),
 datetime.datetime(2023, 1, 26, 0,

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [26]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [28]:
print(pd.DataFrame(lists,columns=['sno','name','num']))

   sno name  num
0    1  aaa   22
1    2  bbb   25
2    3  ccc   24
